### ISSUE TITLE
Bug: autoscaling.virtio-mem is flaky

### ISSUE THREAD

**Issue by Omrigan** [neondatabase/autoscaling#1006] opened 2024-07-11 11:30 UTC
Fails roughly 50% of the time.

**Comment by sharnoff** [comment] 2024-07-11 13:24
@Omrigan how long has it been flaky for? Can you link some example runs?

**Comment by Omrigan** [comment] 2024-07-11 13:43
> @Omrigan how long has it been flaky for? 

I'd assume from the introduction.

> Can you link some example runs?

Your PR: https://github.com/neondatabase/autoscaling/actions/runs/9878750381/job/27283615758#step:14:1034
My PR: https://github.com/neondatabase/autoscaling/actions/runs/9889976645/job/27317397731#step:14:948

I had 3 or 4 such cases, I think.

However, maybe it is not that particular test, here is the other test failing: https://github.com/neondatabase/autoscaling/actions/runs/9890395470/job/27319200362#step:14:987

**Comment by stradig** [comment] 2024-07-15 15:15
We should check if this is only timeouts or if we suspect an actual problem. Until then marking as P1.

**Comment by sharnoff** [comment] 2024-07-16 05:57
Haven't yet had a chance to look at it. However - @Omrigan if you're truly observing it fail 50% of the time, it _may_ be due to your PR. The occurrence you flagged was the first time I'd seen it fail on one of my PRs.

**Comment by sharnoff** [comment] 2024-08-07 17:53
A couple recent runs:

- https://github.com/neondatabase/autoscaling/actions/runs/10288614733/job/28474757879
- https://github.com/neondatabase/autoscaling/actions/runs/10288505505/job/28474375284

Both cases look like they timed out after 5 minutes on downscaling.

**Comment by petuhovskiy** [comment] 2024-10-09 08:06
https://gist.github.com/petuhovskiy/226522b34bd85a3a8d2d8ee88fa43dbd

Tried to reproduce, it failed only once in 360 runs. Let's consider it fixed for now.

**Closed by petuhovskiy** 2024-10-09 08:06 UTC
Labels: a/ci, a/test/flaky, m/good_first_issue
